### ISSUE TITLE
problems with header-names

### ISSUE THREAD

**Issue by ziginfo** [etehel/CSV-Chataigne-Module#1]
Hello Walter
thanks for sharing your module...👍 
your script does not seem support special characters (eg: é, è â, ô, ä, ï etc etc etc) and neither "spaces" in the names of the headers !   => no problem for these characters, when they are present in the words of the info lines; This only concerns the headers (and so : the Data-Container-Field-Names) !! and the script stops loading/executing when it finds such a special character or a "space" in a header-name ! .... (script error : Line 74, column 54 : Unknown function 'set')
and here is another request : would it be possible to add also "tab" as separator ?

**Comment by etehel** [comment]
Hi! I have just fixed that. I let you retry with the new version ;)

**Comment by ziginfo** [comment]
yess it works now;  thanks for your reactivity !!
awesome !! 
cheers ...Z.

**Comment by etehel** [comment]
Nice! I close then
